apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ly7i
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0073-tenant/tkrw-pr712-0075-0073-app/devfile-sample-ly7i@sha256:ed9e51dfaf69c94162c93d27dd59a1c8febead8c62b4255374b56c90309176de
        name: my-nodejs
        resources: {}
status: {}
